import Head from "next/head";
import Image from "next/image";
import { withProtected } from "../src/utils/route";
import styles from "../styles/Home.module.css";

function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <iframe
        src="https://drive.google.com/file/d/12_u2ny6hvR2XK-GjpAUhEq9Eji-Rtbt0/preview"
        width="640"
        height="480"
        allow="autoplay"></iframe>
    </div>
  );
}

export default withProtected(Home);
